### ISSUE TITLE
Scope toggles to immediate descendants to allow for nesting

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/houdini#61]
```scss
/**
 * Show/hide text
 */
.js-houdini .active > .collapse-text-show,
.collapse-text-hide {
	display: none;
	visibility: hidden;
}

.js-houdini .active > .collapse-text-hide {
	display: inline-block;
	visibility: visible;
}
```
